### ISSUE TITLE
Integration for MPK ŁÓDŹ

### ISSUE THREAD

**Issue by pigulson** [PiotrMachowski/Home-Assistant-custom-components-MPK-Rzeszow#1]
Hi,
I noticed that Łódź has a similar webpage with timetables: http://rozklady.lodz.pl/
Would it be possible to create integration for MPK Łódź?

**Comment by PiotrMachowski** [comment]
Hi,
It should be possible

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/Home-Assistant-custom-components-MPK-Lodz
